branches:
  only:
    - master
  except:
    - gh-pages

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  project: src/HyperPropertyDescriptor.sln

before_build:
  - cmd: cd src
  - cmd: nuget restore
  - cmd: cd ..

after_test:
  - ps: .\.nuget\pack.ps1

deploy:
  provider: NuGet
  api_key:
    secure: yNaPU9GGsdDdMjOB5tbQTuIIq4DFHNGUkZP1ZTDDCKQG3g7pZjxcBFZblTMeIawA
  artifact: /.*\.nupkg/
